package com.paradox.zswebsite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessServiceAllPropertiesEquals(BusinessService expected, BusinessService actual) {
        assertBusinessServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessServiceAllUpdatablePropertiesEquals(BusinessService expected, BusinessService actual) {
        assertBusinessServiceUpdatableFieldsEquals(expected, actual);
        assertBusinessServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessServiceAutoGeneratedPropertiesEquals(BusinessService expected, BusinessService actual) {
        assertThat(actual)
            .as("Verify BusinessService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessServiceUpdatableFieldsEquals(BusinessService expected, BusinessService actual) {
        assertThat(actual)
            .as("Verify BusinessService relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIcon()).as("check icon").isEqualTo(expected.getIcon()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessServiceUpdatableRelationshipsEquals(BusinessService expected, BusinessService actual) {
        // empty method
    }
}
