package com.paradox.zswebsite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PageContentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentAllPropertiesEquals(PageContent expected, PageContent actual) {
        assertPageContentAutoGeneratedPropertiesEquals(expected, actual);
        assertPageContentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentAllUpdatablePropertiesEquals(PageContent expected, PageContent actual) {
        assertPageContentUpdatableFieldsEquals(expected, actual);
        assertPageContentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentAutoGeneratedPropertiesEquals(PageContent expected, PageContent actual) {
        assertThat(actual)
            .as("Verify PageContent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentUpdatableFieldsEquals(PageContent expected, PageContent actual) {
        assertThat(actual)
            .as("Verify PageContent relevant properties")
            .satisfies(a -> assertThat(a.getSectionKey()).as("check sectionKey").isEqualTo(expected.getSectionKey()))
            .satisfies(a -> assertThat(a.getContentHtml()).as("check contentHtml").isEqualTo(expected.getContentHtml()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentUpdatableRelationshipsEquals(PageContent expected, PageContent actual) {
        // empty method
    }
}
