package com.paradox.zswebsite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PageContentMediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentMediaAllPropertiesEquals(PageContentMedia expected, PageContentMedia actual) {
        assertPageContentMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertPageContentMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentMediaAllUpdatablePropertiesEquals(PageContentMedia expected, PageContentMedia actual) {
        assertPageContentMediaUpdatableFieldsEquals(expected, actual);
        assertPageContentMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentMediaAutoGeneratedPropertiesEquals(PageContentMedia expected, PageContentMedia actual) {
        assertThat(actual)
            .as("Verify PageContentMedia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentMediaUpdatableFieldsEquals(PageContentMedia expected, PageContentMedia actual) {
        assertThat(actual)
            .as("Verify PageContentMedia relevant properties")
            .satisfies(a -> assertThat(a.getMediaUrl()).as("check mediaUrl").isEqualTo(expected.getMediaUrl()))
            .satisfies(a ->
                assertThat(a.getPageContentMediaType()).as("check pageContentMediaType").isEqualTo(expected.getPageContentMediaType())
            )
            .satisfies(a -> assertThat(a.getCaption()).as("check caption").isEqualTo(expected.getCaption()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageContentMediaUpdatableRelationshipsEquals(PageContentMedia expected, PageContentMedia actual) {
        assertThat(actual)
            .as("Verify PageContentMedia relationships")
            .satisfies(a -> assertThat(a.getPagecontent()).as("check pagecontent").isEqualTo(expected.getPagecontent()));
    }
}
