package com.paradox.zswebsite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProjectImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectImageAllPropertiesEquals(ProjectImage expected, ProjectImage actual) {
        assertProjectImageAutoGeneratedPropertiesEquals(expected, actual);
        assertProjectImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectImageAllUpdatablePropertiesEquals(ProjectImage expected, ProjectImage actual) {
        assertProjectImageUpdatableFieldsEquals(expected, actual);
        assertProjectImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectImageAutoGeneratedPropertiesEquals(ProjectImage expected, ProjectImage actual) {
        assertThat(actual)
            .as("Verify ProjectImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectImageUpdatableFieldsEquals(ProjectImage expected, ProjectImage actual) {
        assertThat(actual)
            .as("Verify ProjectImage relevant properties")
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getCaption()).as("check caption").isEqualTo(expected.getCaption()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectImageUpdatableRelationshipsEquals(ProjectImage expected, ProjectImage actual) {
        assertThat(actual)
            .as("Verify ProjectImage relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
