package com.paradox.zswebsite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProjectMediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectMediaAllPropertiesEquals(ProjectMedia expected, ProjectMedia actual) {
        assertProjectMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertProjectMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectMediaAllUpdatablePropertiesEquals(ProjectMedia expected, ProjectMedia actual) {
        assertProjectMediaUpdatableFieldsEquals(expected, actual);
        assertProjectMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectMediaAutoGeneratedPropertiesEquals(ProjectMedia expected, ProjectMedia actual) {
        assertThat(actual)
            .as("Verify ProjectMedia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectMediaUpdatableFieldsEquals(ProjectMedia expected, ProjectMedia actual) {
        assertThat(actual)
            .as("Verify ProjectMedia relevant properties")
            .satisfies(a -> assertThat(a.getMediaUrl()).as("check mediaUrl").isEqualTo(expected.getMediaUrl()))
            .satisfies(a -> assertThat(a.getProjectMediaType()).as("check projectMediaType").isEqualTo(expected.getProjectMediaType()))
            .satisfies(a -> assertThat(a.getCaption()).as("check caption").isEqualTo(expected.getCaption()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectMediaUpdatableRelationshipsEquals(ProjectMedia expected, ProjectMedia actual) {
        assertThat(actual)
            .as("Verify ProjectMedia relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
