package com.paradox.zswebsite.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VisitorLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitorLogAllPropertiesEquals(VisitorLog expected, VisitorLog actual) {
        assertVisitorLogAutoGeneratedPropertiesEquals(expected, actual);
        assertVisitorLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitorLogAllUpdatablePropertiesEquals(VisitorLog expected, VisitorLog actual) {
        assertVisitorLogUpdatableFieldsEquals(expected, actual);
        assertVisitorLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitorLogAutoGeneratedPropertiesEquals(VisitorLog expected, VisitorLog actual) {
        assertThat(actual)
            .as("Verify VisitorLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitorLogUpdatableFieldsEquals(VisitorLog expected, VisitorLog actual) {
        assertThat(actual)
            .as("Verify VisitorLog relevant properties")
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getPageVisited()).as("check pageVisited").isEqualTo(expected.getPageVisited()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()))
            .satisfies(a -> assertThat(a.getVisitTimestamp()).as("check visitTimestamp").isEqualTo(expected.getVisitTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitorLogUpdatableRelationshipsEquals(VisitorLog expected, VisitorLog actual) {
        // empty method
    }
}
