# .github/workflows/deploy-full-stack.yml

name: Deploy Backend and Frontend

on:
  push:
    branches: ['master'] # Runs whenever you push to the 'main' branch

jobs:
  # === JOB 1: DEPLOY BACKEND ===
  deploy-backend:
    name: Deploy Backend to Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Make sure these secrets exist in your GitHub repo from your previous backend setup
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Backend with Maven
        run: ./mvnw -ntp -Pprod clean package -DskipTests

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'zoranstepanoski-prof-api'
          region: 'europe-central2'
          source: './target' # Points to the folder containing your JAR file

  # === JOB 2: DEPLOY FRONTEND (depends on backend) ===
  deploy-frontend:
    name: Deploy Frontend to Firebase
    runs-on: ubuntu-latest
    needs: deploy-backend # This line is CRITICAL. It tells this job to wait for 'deploy-backend' to succeed.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend
        run: npm ci && npm run webapp:prod

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' # The secret we created in Step 2
          projectId: 'tactile-ripsaw-474418-j1' # Your Project ID
