name: GCP Deploy Backend

on:
  push:
    branches:
      - main
      - master

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-central2
  SERVICE_NAME: zoranstepanoski-prof-api
  REPO_NAME: zoranstepanoski-prof-api-repo

jobs:
  deploy-backend:
    name: Deploy Backend to Google Cloud Run
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest -f fly/backend/Dockerfile.backend .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest

      - name: Deploy new revision to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest
          flags: '--allow-unauthenticated'
          env_vars: |
            SPRING_PROFILES_ACTIVE=prod
            SPRING_DATASOURCE_URL=jdbc:postgresql://${{ secrets.SUPABASE_DB_HOST }}:5432/${{ secrets.SUPABASE_DB_NAME }}?sslmode=require
            SPRING_DATASOURCE_USERNAME=${{ secrets.SUPABASE_DB_USER }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }}
            JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=${{ secrets.JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET }}
            MAILJET_API_KEY=${{ secrets.MAILJET_API_KEY }}
            MAILJET_SECRET_KEY=${{ secrets.MAILJET_SECRET_KEY }}
