name: Supabase Keep Alive

on:
  schedule:
    # Pokreće se 3 puta dnevno (na svakih 8 sati: 00:00, 08:00 i 16:00 po UTC vremenu)
    - cron: '0 */8 * * *'
  workflow_dispatch: # Omogućava ti da pokreneš skriptu i ručno dugmetom

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend to Wake Up Database
        run: |
          # Šalje HEAD request da bi probudio bazu
          curl -I https://zoranstepanoski-prof-api-yqiyrjxyeq-lm.a.run.app/api/skills
